@extends('admin.layout.default')

<link rel="stylesheet" type="text/css" href="/css/forestry.css">

@section('body')
    <h1>
        Структура
    </h1>
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead>
            <tr class="bg-primary">
                <th>
                    Участковое лесничество
                </th>
                <th>
                    Общая площадь
                </th>
                <th>
                    Лесорастительная зона
                </th>
                <th>
                    Перечень лесных кварталов
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Мандрогское
                </td>
                <td>
                    21496
                </td>
                <td>
                    Таежная
                </td>
                <td>
                    1-187
                </td>
            </tr>
            <tr>
                <td>
                    Кондушское
                </td>
                <td>
                    20664
                </td>
                <td>
                    Таежная
                </td>
                <td>
                    1-120
                </td>
            </tr>
            <tr>
                <td>
                    Свирское
                </td>
                <td>
                    27415
                </td>
                <td>
                    Таежная
                </td>
                <td>
                    1-220
                </td>
            </tr>
            <tr>
                <td>
                    Лодейнопольское
                </td>
                <td>
                    19176
                </td>
                <td>
                    Таежная
                </td>
                <td>
                    1-96
                </td>
            </tr>
            <tr>
                <td>
                    Тененское
                </td>
                <td>
                    22963
                </td>
                <td>
                    Таежная
                </td>
                <td>
                    1-98
                </td>
            </tr>
            <tr>
                <td>
                    Шоткусское
                </td>
                <td>
                    13717
                </td>
                <td>
                    Таежная
                </td>
                <td>
                    1-62
                </td>
            </tr>
            <tr>
                <td>
                    Люговское
                </td>
                <td>
                    19231
                </td>
                <td>
                    Таежная
                </td>
                <td>
                    1-89
                </td>
            </tr>
            <tr>
                <td>
                    Шапшинское
                </td>
                <td>
                    17655
                </td>
                <td>
                    Таежная
                </td>
                <td>
                    1-153
                </td>
            </tr>
            <tr>
                <td>
                    Доможировское
                </td>
                <td>
                    17655
                </td>
                <td>
                    Таежная
                </td>
                <td>
                    1-115
                </td>
            </tr>
            <tr>
                <td>
                    Свирское сельское
                </td>
                <td>
                    30672
                </td>
                <td>
                    Таежная
                </td>
                <td>
                    1-75, 101-126, 201-332
                </td>
            </tr>
            <tr>
                <td>
                    Яровщинское
                </td>
                <td>
                    23946
                </td>
                <td>
                    Таежная
                </td>
                <td>
                    1-142
                </td>
            </tr>
            <tr>
                <td>
                    Алеховщинское
                </td>
                <td>
                    25848
                </td>
                <td>
                    Таежная
                </td>
                <td>
                    1-124
                </td>
            </tr>
            <tr>
                <td>
                    Ребовское
                </td>
                <td>
                    41796
                </td>
                <td>
                    Таежная
                </td>
                <td>
                    1-204
                </td>
            </tr>
            <tr>
                <td>
                    Пирозерское
                </td>
                <td>
                    25212
                </td>
                <td>
                    Таежная
                </td>
                <td>
                    1-136
                </td>
            </tr>
            <tr>
                <td>
                    Алеховщинское сельское
                </td>
                <td>
                    23416
                </td>
                <td>
                    Таежная
                </td>
                <td>
                    1-178
                </td>
            </tr>
            <tr>
                <td>
                    Тервеническое
                </td>
                <td>
                    35998
                </td>
                <td>
                    Таежная
                </td>
                <td>
                    1-244
                </td>
            </tr>
            <tr>
                <td>
                    Всего по лесничеству
                </td>
                <td>
                    401899
                </td>
                <td>
                    Таежная
                </td>
                <td>
                    2401
                </td>
            </tr>
            </tbody>
        </table>
    </div>

@endsection
